INSERT INTO books VALUES(1,'Genesis',50,0,'["gen"]');
INSERT INTO books VALUES(2,'Exodus',40,0,'["exo"]');
INSERT INTO books VALUES(3,'Leviticus',27,0,'["lev"]');
INSERT INTO books VALUES(4,'Numbers',36,0,'["num"]');
INSERT INTO books VALUES(5,'Deuteronomy',34,0,'["deu", "deut"]');
INSERT INTO books VALUES(6,'Joshua',24,0,'["josh", "jos"]');
INSERT INTO books VALUES(7,'Judges',21,0,'["judg"]');
INSERT INTO books VALUES(8,'Ruth',4,0,'["ruth"]');
INSERT INTO books VALUES(9,'1 Samuel',31,0,'["1 sam", "1 sa"]');
INSERT INTO books VALUES(10,'2 Samuel',24,0,'["2 sam", "2 sa"]');
INSERT INTO books VALUES(11,'1 Kings',22,0,'["1 king", "1 kin"]');
INSERT INTO books VALUES(12,'2 Kings',25,0,'["2 king", "2 kin"]');
INSERT INTO books VALUES(13,'1 Chronicles',29,0,'["1 chron", "1 chro", "1 chr"]');
INSERT INTO books VALUES(14,'2 Chronicles',36,0,'["2 chron", "2 chro", "2 chr"]');
INSERT INTO books VALUES(15,'Ezra',10,0,'["ezra", "ezr"]');
INSERT INTO books VALUES(16,'Nehemiah',13,0,'["neh"]');
INSERT INTO books VALUES(17,'Esther',10,0,'["esth"]');
INSERT INTO books VALUES(18,'Job',42,0,'["job"]');
INSERT INTO books VALUES(19,'Psalm',150,0,'["psa"]');
INSERT INTO books VALUES(20,'Proverbs',31,0,'["pro", "prov"]');
INSERT INTO books VALUES(21,'Ecclesiastes',12,0,'["eccl", "ecc"]');
INSERT INTO books VALUES(22,'Song of Songs',8,0,'["ss", "s.s.", "song", "son"]');
INSERT INTO books VALUES(23,'Isaiah',66,0,'["isa"]');
INSERT INTO books VALUES(24,'Jeremiah',52,0,'["jer"]');
INSERT INTO books VALUES(25,'Lamentations',5,0,'["lam"]');
INSERT INTO books VALUES(26,'Ezekiel',48,0,'["eze", "ezek"]');
INSERT INTO books VALUES(27,'Daniel',12,0,'["dan"]');
INSERT INTO books VALUES(28,'Hosea',14,0,'["hosea", "hos"]');
INSERT INTO books VALUES(29,'Joel',3,0,'["joel"]');
INSERT INTO books VALUES(30,'Amos',9,0,'["amos"]');
INSERT INTO books VALUES(31,'Obadiah',1,0,'["oba"]');
INSERT INTO books VALUES(32,'Jonah',4,0,'["jonah", "jon"]');
INSERT INTO books VALUES(33,'Micah',7,0,'["micah", "mic"]');
INSERT INTO books VALUES(34,'Nahum',3,0,'["nahum", "nah"]');
INSERT INTO books VALUES(35,'Habakkuk',3,0,'["hab"]');
INSERT INTO books VALUES(36,'Zephaniah',3,0,'["zeph", "zep"]');
INSERT INTO books VALUES(37,'Haggai',2,0,'["hag"]');
INSERT INTO books VALUES(38,'Zechariah',14,0,'["zech", "zec"]');
INSERT INTO books VALUES(39,'Malachi',4,0,'["mal"]');
INSERT INTO books VALUES(40,'Matthew',28,1,'["matt", "mat"]');
INSERT INTO books VALUES(41,'Mark',16,1,'["mar", "mark", "mk"]');
INSERT INTO books VALUES(42,'Luke',24,1,'["luke", "luk"]');
INSERT INTO books VALUES(43,'John',21,1,'["john", "joh"]');
INSERT INTO books VALUES(44,'Acts',28,1,'["acts"]');
INSERT INTO books VALUES(45,'Romans',16,1,'["rom"]');
INSERT INTO books VALUES(46,'1 Corinthians',16,1,'["1 cor", "1 co"]');
INSERT INTO books VALUES(47,'2 Corinthians',13,1,'["2 cor", "2 co"]');
INSERT INTO books VALUES(48,'Galatians',6,1,'["gal"]');
INSERT INTO books VALUES(49,'Ephesians',6,1,'["eph"]');
INSERT INTO books VALUES(50,'Philippians',4,1,'["phil"]');
INSERT INTO books VALUES(51,'Colossians',4,1,'["col"]');
INSERT INTO books VALUES(52,'1 Thessalonians',5,1,'["1 thes", "1 th", "1 the"]');
INSERT INTO books VALUES(53,'2 Thessalonians',3,1,'["2 thes", "2 th", "2 the"]');
INSERT INTO books VALUES(54,'1 Timothy',6,1,'["1 tim", "1 ti"]');
INSERT INTO books VALUES(55,'2 Timothy',4,1,'["2 tim", "2 ti"]');
INSERT INTO books VALUES(56,'Titus',3,1,'["tit", "titus"]');
INSERT INTO books VALUES(57,'Philemon',1,1,'["philem", "phile", "phlm"]');
INSERT INTO books VALUES(58,'Hebrews',13,1,'["heb"]');
INSERT INTO books VALUES(59,'James',5,1,'["james", "jam"]');
INSERT INTO books VALUES(60,'1 Peter',5,1,'["1 pet", "1 pe"]');
INSERT INTO books VALUES(61,'2 Peter',3,1,'["2 pet", "2 pe"]');
INSERT INTO books VALUES(62,'1 John',5,1,'["1 joh", "1 jo","1 jn"]');
INSERT INTO books VALUES(63,'2 John',1,1,'["2 joh", "2 jo","2 jn"]');
INSERT INTO books VALUES(64,'3 John',1,1,'["3 joh", "3 jo","3 jn"]');
INSERT INTO books VALUES(65,'Jude',1,1,'["jude"]');
INSERT INTO books VALUES(66,'Revelation',22,1,'["rev"]');
